# Generated by Django 4.2.7 on 2023-12-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
