# Generated by Django 5.0 on 2023-12-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_document_date_added_document_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
