# Generated by Django 5.0 on 2023-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_document_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
