# Generated by Django 5.0 on 2023-12-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_rename_document_chapter_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'parent_chapter', 'order')},
        ),
    ]
