# Generated by Django 5.0 on 2023-12-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='guessed_time',
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='slides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='slides_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='time_estimated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
