# Generated by Django 5.0 on 2023-12-12 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_chapter_guessed_time_chapter_pages_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='time_estimated',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimated',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
