# Generated by Django 5.0 on 2023-12-12 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_chapter_time_estimated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='time_estimated',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
