# Generated by Django 5.0 on 2023-12-15 09:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_chapter_time_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_estimated',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
